# NumPy数组与矢量计算

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

## 1. NumPy简单应用

In [3]:
def python_sum(n):
    #range函数产生包含0至n的整数元组，用list函数转换成列表
     x = list(range(n))
     y = list(range(n))
     z = []
     for i in range(len(x)):
          y[i] = i**2
          z.append(x[i]+y[i])
     return z
python_sum(5)

[0, 2, 6, 12, 20]

使用NumPy实现上面代码：

In [4]:
def numpy_sum(n):
    x =np.arange(n)            #arange函数创建包含0至n的整数数组
    y = np.arange(n)**2
    z = x + y
    return z
python_sum(5)

[0, 2, 6, 12, 20]

比较两者用时

In [5]:
#测试python_sum函数的执行时间
from datetime import datetime
n=1000000
start_time = datetime.now()
python_sum(n)
time_interval = datetime.now()-start_time
print(time_interval)
#测试numpy_sum函数的执行时间
n=1000000
start_time = datetime.now()
b = numpy_sum(n)
time_interval = datetime.now()-start_time
print(time_interval)

del b,n,start_time,time_interval

0:00:00.303211
0:00:00.003999


## 2. NumPy数组对象

### 2.1 创建数组对象

In [8]:
arr1 =np.array([1,2,3,4])                   #创建一维数组
print('一维数组:',arr1)
arr2 = np.array([[1,2,3],[4,5,6]])          #创建二维数组
print('二维数组:',arr2)
arr3 =np.array([1,2,3,4],ndmin=3)           #设置最小维度3
print('三维数组:',arr3)
arr4 = np.array([1,2,3.4], dtype=complex)   #指定数据类型dtype为复数
print('复数数组:',arr4)
del arr1,arr3,arr4

一维数组: [1 2 3 4]
二维数组: [[1 2 3]
 [4 5 6]]
三维数组: [[[1 2 3 4]]]
复数数组: [1. +0.j 2. +0.j 3.4+0.j]


### 2.2 选取数组元素

In [9]:
# 以二维数组arr2为例
# 选取数组中的元素
print('选取数组中的元素:',arr2[1,2])
# 选取数组中的行
print('选取数组中的行:',arr2[1,:])
# 选取数组中的列
print('选取数组中的列:',arr2[:,1])
# 选取数组中的多个元素
print('选取数组中的多个元素:',arr2[1,0:2])
# 选取数组中的多行多列
print('选取数组中的多行多列:',arr2[0:2,1:3])
# 选取数组中的多个不相邻的元素
print('选取数组中的多个不相邻的元素:',arr2[[0,1],[1,2]])
del arr2

选取数组中的元素: 6
选取数组中的行: [4 5 6]
选取数组中的列: [2 5]
选取数组中的多个元素: [4 5]
选取数组中的多行多列: [[2 3]
 [5 6]]
选取数组中的多个不相邻的元素: [2 6]


### 2.3 数组的属性

In [31]:
# 数组的属性
## 数组的形状
print('数组的形状:',arr2.shape)
## 数组的维度
print('数组的维度:',arr2.ndim)
## 数组的元素个数
print('数组的元素个数:',arr2.size)
## 数组的数据类型
print('数组的数据类型:',arr2.dtype)
## 数组的每个元素所占字节数
print('数组的每个元素所占字节数:',arr2.itemsize)

数组的形状: (2, 3)
数组的维度: 2
数组的元素个数: 6
数组的数据类型: int32
数组的每个元素所占字节数: 4


### 2.4 创建数组的其他方法

In [27]:
# 创建数组的其他方法
## 使用arange函数创建数组
print('使用arange函数创建数组:',np.arange(0,5))#创建等差数列
## 使用linspace函数创建数组
print('使用linspace函数创建数组:',np.linspace(0,1,5))#创建等差数列
## 使用logspace函数创建数组
print('使用logspace函数创建数组:',np.logspace(0,2,5))#创建等比数列
## 使用zeros函数创建数组
print('使用zeros函数创建数组:',np.zeros((2,3)))#zeros函数创建全0数组
## 使用ones函数创建数组
print('使用ones函数创建数组:',np.ones((3,3)))#ones函数创建全1数组
## 使用eye函数创建数组
print('使用eye函数创建数组:',np.eye(3))#eye函数创建单位矩阵
## 使用diag函数创建数组
print('使用diag函数创建数组:',np.diag([1,2,3]))#diag函数创建对角矩阵
## 使用empty函数创建数组
print('使用empty函数创建数组:',np.empty((2,3)))#empty函数创建的数组元素的值是随机的

使用arange函数创建数组: [0 1 2 3 4]
使用linspace函数创建数组: [0.   0.25 0.5  0.75 1.  ]
使用logspace函数创建数组: [  1.           3.16227766  10.          31.6227766  100.        ]
使用zeros函数创建数组: [[0. 0. 0.]
 [0. 0. 0.]]
使用ones函数创建数组: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
使用eye函数创建数组: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
使用diag函数创建数组: [[1 0 0]
 [0 2 0]
 [0 0 3]]
使用empty函数创建数组: [[0. 0. 0.]
 [0. 0. 0.]]


### 2.5 NumPy的数据类型

In [38]:
# 数组的数据类型转换
## 使用astype函数转换数组的数据类型
arr1 = np.array([1,2,3,4])
print('转换前数组的数据类型:',arr1.dtype)#dtype属性查看数组的数据类型
arr2 = arr1.astype(np.float64)
print('转换后数组的数据类型:',arr2.dtype)
## 使用astype函数将字符串数组转换为数值数组
arr3 = np.array(['1','2','3','4'])
print('转换前数组的数据类型:',arr3.dtype)
arr4 = arr3.astype(np.int64)
print('转换后数组的数据类型:',arr4.dtype)
## 使用astype函数将数值数组转换为字符串数组
arr5 = np.array([1,2,3,4])
print('转换前数组的数据类型:',arr5.dtype)
arr6 = arr5.astype(np.str_)
print(arr6)
print('转换后数组的数据类型:',arr6.dtype)

del arr1,arr2,arr3,arr4,arr5,arr6

转换前数组的数据类型: int32
转换后数组的数据类型: float64
转换前数组的数据类型: <U1
转换后数组的数据类型: int64
转换前数组的数据类型: int32
['1' '2' '3' '4']
转换后数组的数据类型: <U11


In [61]:
# 自定义数据类型
## 使用dtype函数自定义数据类型
dt = np.dtype([('name',np.str_,40),('numitems',np.int32),('price',np.float32)])
print('自定义数据类型:',dt)
## 使用自定义数据类型创建数组
itemz = np.array([('Meaning of life DVD',42,3.14),
                  ('Butter',13,2.72)],dtype=dt)
print('使用自定义数据类型创建数组:',itemz)
## 访问数组中的元素
print('访问数组中的元素:',itemz[1])
print('访问数组中的元素:',itemz[1]['name'])

del dt,itemz

自定义数据类型: [('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')]
使用自定义数据类型创建数组: [('Meaning of life DVD', 42, 3.14) ('Butter', 13, 2.72)]
访问数组中的元素: ('Butter', 13, 2.72)
访问数组中的元素: Butter


NumPy数组一般是同质的，即数组中的所有元素都是相同的数据类型。如果想创建异构数据类型的数组，就需要先自定义异构数据类型，如dt数据类型，它包括一个用字符串表示的产品名称和一个用浮点数表示的产品价格，然后在创建数组的函数中使用dtype参数来指定数据类型为dt(自定义数据类型)。

## 3. NumPy数组操作

### 3.1 数组的索引和切片

In [67]:
# 数组的索引和切片
## 一维数组的索引和切片
arr1 = np.arange(10)
print('一维数组的索引和切片:',arr1)
print('一维数组的索引和切片:',arr1[5])
print('一维数组的索引和切片:',arr1[3:5])
print('一维数组的索引和切片:',arr1[:5])
print('一维数组的索引和切片:',arr1[3:])
print('一维数组的索引和切片:',arr1[1:6:2])
print('一维数组的索引和切片:',arr1[::-1])
del arr1

一维数组的索引和切片: [0 1 2 3 4 5 6 7 8 9]
一维数组的索引和切片: 5
一维数组的索引和切片: [3 4]
一维数组的索引和切片: [0 1 2 3 4]
一维数组的索引和切片: [3 4 5 6 7 8 9]
一维数组的索引和切片: [1 3 5]
一维数组的索引和切片: [9 8 7 6 5 4 3 2 1 0]


In [69]:
# 多维数组的索引和切片
arr2 = np.arange(12).reshape(3, 4)
print('多维数组的索引和切片:\n', arr2)
print('多维数组的索引和切片:', arr2[2])
print('多维数组的索引和切片:', arr2[1, 2])
print('多维数组的索引和切片:', arr2[1][2])
print('多维数组的索引和切片:', arr2[1, :])
print('多维数组的索引和切片:', arr2[:, 1])
print('多维数组的索引和切片:\n', arr2[1:3, 1:3])
del arr2

多维数组的索引和切片:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
多维数组的索引和切片: [ 8  9 10 11]
多维数组的索引和切片: 6
多维数组的索引和切片: 6
多维数组的索引和切片: [4 5 6 7]
多维数组的索引和切片: [1 5 9]
多维数组的索引和切片:
 [[ 5  6]
 [ 9 10]]


In [75]:
# 整数索引
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[(0,1,2),(0,1,0)]       #获取a[0,0],a[1,1],a[2,0]元素组成数组b
print(a)
print(b)
#获取a数组上下左右四个角上的元素
b = a[(0,0,2,2),(0,2,0,2)]    #获取a[0,0],a[0,2],a[2,0],a[2,2]元素
print(b)

del a,b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 7]
[1 3 7 9]


In [76]:
# 布尔索引
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a > 5
print(b)
print(a[b])
print(a[a > 5])
del a, b

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[6 7 8 9]


### 3.2 修改数组形状

In [83]:
# 用元组设置维度修改数组形状的方法
arr1 = np.arange(10)
print('修改前数组的形状:',arr1.shape)
arr1.shape = 2,5
print('修改后数组的形状:',arr1.shape)
print('修改后数组:\n',arr1)
arr1.shape = 5,-1
print('修改后数组的形状:',arr1.shape)
print('修改后数组:\n',arr1)
del arr1

修改前数组的形状: (10,)
修改后数组的形状: (2, 5)
修改后数组:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
修改后数组的形状: (5, 2)
修改后数组:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [93]:
# reshape方法修改数组形状的方法
arr2 = np.arange(10)
print('修改前数组的形状:',arr2.shape)
arr3 = arr2.reshape(2,5)#reshape方法返回修改后的数组
print('修改后数组的形状:',arr3.shape)
print('修改后数组:\n',arr3)
arr4 = arr2.reshape(5,-1)
print('修改后数组的形状:',arr4.shape)
print('修改后数组:\n',arr4)
del arr2,arr3,arr4

修改前数组的形状: (10,)
修改后数组的形状: (2, 5)
修改后数组:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
修改后数组的形状: (5, 2)
修改后数组:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [91]:
# resize方法修改数组形状的方法
arr5 = np.arange(10)
print('修改前数组的形状:',arr5.shape)
arr5.resize(2,5)#resize方法修改数组形状时会修改原数组
print('修改后数组的形状:',arr5.shape)
print('修改后数组:\n',arr5)
arr6 = arr5.copy()
print('修改前数组的形状:',arr6.shape)
arr6.resize(5,2)
print('修改后数组的形状:',arr6.shape)
print('修改后数组:\n',arr6)
del arr5,arr6

修改前数组的形状: (10,)
修改后数组的形状: (2, 5)
修改后数组:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
修改前数组的形状: (2, 5)
修改后数组的形状: (5, 3)
修改后数组:
 [[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 0]
 [0 0 0]]


### 3.3 数组的展平

In [94]:
# ravel/faltten方法修改数组形状的方法
arr7 = np.arange(10).reshape(2,5)
print('修改前数组的形状:',arr7.shape)
arr8 = arr7.ravel()#ravel方法返回修改后的数组
print('修改后数组的形状:',arr8.shape)
print('修改后数组:\n',arr8)
arr9 = arr7.flatten()#flatten方法返回修改后的数组
print('修改后数组的形状:',arr9.shape)
print('修改后数组:\n',arr9)
del arr7,arr8,arr9


修改前数组的形状: (2, 5)
修改后数组的形状: (10,)
修改后数组:
 [0 1 2 3 4 5 6 7 8 9]
修改后数组的形状: (10,)
修改后数组:
 [0 1 2 3 4 5 6 7 8 9]


### 3.4 数组转置和轴对换

In [95]:
# transpose方法修改数组形状的方法
arr10 = np.arange(12).reshape(3,4)
print('修改前数组的形状:\n',arr10) 
arr11 = arr10.transpose()#transpose方法返回修改后的数组
print('修改后数组的形状:\n',arr11)
del arr10,arr11

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改后数组的形状:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [96]:
# ndarray.T属性修改数组形状的方法
arr12 = np.arange(12).reshape(3,4)
print('修改前数组的形状:\n',arr12)
arr13 = arr12.T#T属性返回修改后的数组
print('修改后数组的形状:\n',arr13)
del arr12,arr13

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改后数组的形状:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [97]:
# rollaxis方法修改数组形状的方法
arr14 = np.arange(12).reshape(3,4)
print('修改前数组的形状:\n',arr14)
arr15 = np.rollaxis(arr14,1)#rollaxis方法返回修改后的数组
print('修改后数组的形状:\n',arr15)
del arr14,arr15

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改后数组的形状:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [98]:
# swapaxes方法修改数组形状的方法
arr16 = np.arange(12).reshape(3,4)
print('修改前数组的形状:\n',arr16)
arr17 = np.swapaxes(arr16,0,1)#swapaxes方法返回修改后的数组
print('修改后数组的形状:\n',arr17)
del arr16,arr17

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改后数组的形状:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 3.5 数组的链接

In [99]:
# concatenate方法修改数组形状的方法
arr18 = np.arange(12).reshape(3,4)
arr19 = np.arange(12,24).reshape(3,4)
print('修改前数组的形状:\n',arr18)
print('修改前数组的形状:\n',arr19)
arr20 = np.concatenate((arr18,arr19),axis=0)#concatenate方法返回修改后的数组
print('修改后数组的形状:\n',arr20)
arr21 = np.concatenate((arr18,arr19),axis=1)#concatenate方法返回修改后的数组
print('修改后数组的形状:\n',arr21)
del arr18,arr19,arr20,arr21

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改前数组的形状:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
修改后数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
修改后数组的形状:
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [105]:
# stack方法修改数组形状的方法
arr22 = np.arange(12).reshape(3,4)
arr23 = np.arange(12,24).reshape(3,4)
print('修改前数组的形状:\n',arr22)
print('修改前数组的形状:\n',arr23)
arr24 = np.stack((arr22,arr23),axis=0)#stack方法返回修改后的数组
print('修改后数组的形状:\n',arr24.shape,'\n',arr24)
arr25 = np.stack((arr22,arr23),axis=1)#stack方法返回修改后的数组
print('修改后数组的形状:\n',arr25.shape,'\n',arr25)
arr26 = np.stack((arr22,arr23),axis=2)#stack方法返回修改后的数组
print('修改后数组的形状:\n',arr26.shape,'\n',arr26)
del arr22,arr23,arr24,arr25,arr26

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改前数组的形状:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
修改后数组的形状:
 (2, 3, 4) 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
修改后数组的形状:
 (3, 2, 4) 
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
修改后数组的形状:
 (3, 4, 2) 
 [[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [106]:
# hstack方法修改数组形状的方法
arr27 = np.arange(12).reshape(3,4)
arr28 = np.arange(12,24).reshape(3,4)
print('修改前数组的形状:\n',arr27)
print('修改前数组的形状:\n',arr28)
arr29 = np.hstack((arr27,arr28))#hstack方法返回修改后的数组
print('修改后数组的形状:\n',arr29.shape,'\n',arr29)
del arr27,arr28,arr29

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改前数组的形状:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
修改后数组的形状:
 (3, 8) 
 [[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [107]:
# vstack方法修改数组形状的方法
arr30 = np.arange(12).reshape(3,4)
arr31 = np.arange(12,24).reshape(3,4)
print('修改前数组的形状:\n',arr30)
print('修改前数组的形状:\n',arr31)
arr32 = np.vstack((arr30,arr31))#vstack方法返回修改后的数组
print('修改后数组的形状:\n',arr32.shape,'\n',arr32)
del arr30,arr31,arr32

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改前数组的形状:
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
修改后数组的形状:
 (6, 4) 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### 3.6 数组的分割

In [110]:
# split方法修改数组形状的方法
arr33 = np.arange(16).reshape(4,4)
print('修改前数组的形状:\n',arr33)
arr34 = np.split(arr33,2,axis=0)#split方法返回修改后的数组
print('修改后数组的形状:\n',arr34[0].shape,'\n',arr34[0])
print('修改后数组的形状:\n',arr34[1].shape,'\n',arr34[1])
arr35 = np.split(arr33,2,axis=1)#split方法返回修改后的数组
print('修改后数组的形状:\n',arr35[0].shape,'\n',arr35[0])
print('修改后数组的形状:\n',arr35[1].shape,'\n',arr35[1])
del arr33,arr34,arr35

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
修改后数组的形状:
 (2, 4) 
 [[0 1 2 3]
 [4 5 6 7]]
修改后数组的形状:
 (2, 4) 
 [[ 8  9 10 11]
 [12 13 14 15]]
修改后数组的形状:
 (4, 2) 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
修改后数组的形状:
 (4, 2) 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [111]:
# hsplit方法修改数组形状的方法
arr36 = np.arange(16).reshape(4,4)
print('修改前数组的形状:\n',arr36)
arr37 = np.hsplit(arr36,2)#hsplit方法返回修改后的数组
print('修改后数组的形状:\n',arr37[0].shape,'\n',arr37[0])
print('修改后数组的形状:\n',arr37[1].shape,'\n',arr37[1])
del arr36,arr37

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
修改后数组的形状:
 (4, 2) 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
修改后数组的形状:
 (4, 2) 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [112]:
# vsplit方法修改数组形状的方法
arr38 = np.arange(16).reshape(4,4)
print('修改前数组的形状:\n',arr38)
arr39 = np.vsplit(arr38,2)#vsplit方法返回修改后的数组
print('修改后数组的形状:\n',arr39[0].shape,'\n',arr39[0])
print('修改后数组的形状:\n',arr39[1].shape,'\n',arr39[1])
del arr38,arr39

修改前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
修改后数组的形状:
 (2, 4) 
 [[0 1 2 3]
 [4 5 6 7]]
修改后数组的形状:
 (2, 4) 
 [[ 8  9 10 11]
 [12 13 14 15]]


### 3.7 数组转换

In [115]:
# 数组转换
# 将数组转换成列表
arr40 = np.arange(12).reshape(3,4)
print('转换前数组的形状:\n',arr40)
arr41 = arr40.tolist()#tolist方法返回转换后的列表
print('转换后数组的形状:\n',arr41)
del arr40,arr41

转换前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转换后数组的形状:
 [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


### 3.8 添加/删除数组元素

In [134]:
# append方法转换数组,axis参数修改添加方向
# 用法为：np.append(arr,values,axis=None)
arr42 = np.arange(12).reshape(3,4)
print('转换前数组的形状:\n',arr42)
arr43 = np.append(arr42,[12,13,14,15])#append方法返回转换后的数组
print('转换后数组的形状:\n',arr43)
arr44 = np.append(arr42,[[12,13,14,15]],axis=0)#append方法返回转换后的数组
print('转换后数组的形状:\n',arr44)
arr45 = np.append(arr42,[[12],[13],[14]],axis=1)#append方法返回转换后的数组
# append实际上是将数组转换成列表，然后添加元素，最后再转换成数组，即对行的操作
print('转换后数组的形状:\n',arr45)
del arr42,arr43,arr44,arr45

转换前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转换后数组的形状:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
转换后数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
转换后数组的形状:
 [[ 0  1  2  3 12]
 [ 4  5  6  7 13]
 [ 8  9 10 11 14]]


In [137]:
# insert方法转换数组,axis参数修改添加方向
# 用法为np.insert(arr,obj,values,axis=None)
arr46 = np.arange(12).reshape(3,4)
print('转换前数组的形状:\n',arr46)
arr47 = np.insert(arr46,2,[12,13,14,15])#insert方法返回转换后的数组
print('转换后数组的形状:\n',arr47)
arr48 = np.insert(arr46,2,[[12,13,14,15]],axis=0)#insert方法返回转换后的数组
print('转换后数组的形状:\n',arr48)
arr49 = np.insert(arr46,2,[[12,13,14]],axis=1)#insert方法返回转换后的数组
print('转换后数组的形状:\n',arr49)
arr50 = np.insert(arr46,2,[[12],[13],[14]],axis=1)#insert方法返回转换后的数组
print('转换后数组的形状:\n',arr50)
del arr46,arr47,arr48,arr49,arr50

转换前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转换后数组的形状:
 [ 0  1 12 13 14 15  2  3  4  5  6  7  8  9 10 11]
转换后数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]
 [ 8  9 10 11]]
转换后数组的形状:
 [[ 0  1 12  2  3]
 [ 4  5 13  6  7]
 [ 8  9 14 10 11]]
转换后数组的形状:
 [[ 0  1 12 13 14  2  3]
 [ 4  5 12 13 14  6  7]
 [ 8  9 12 13 14 10 11]]


In [138]:
# delete方法转换数组,axis参数修改添加方向
# 用法为delete(数组名,索引或索引列表,axis=0或1)
arr51 = np.arange(12).reshape(3,4)
print('转换前数组的形状:\n',arr51)
arr52 = np.delete(arr51,2)#delete方法返回转换后的数组
print('转换后数组的形状:\n',arr52)
arr53 = np.delete(arr51,2,axis=0)#delete方法返回转换后的数组
print('转换后数组的形状:\n',arr53)
arr54 = np.delete(arr51,2,axis=1)#delete方法返回转换后的数组
print('转换后数组的形状:\n',arr54)
del arr51,arr52,arr53,arr54

转换前数组的形状:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转换后数组的形状:
 [ 0  1  3  4  5  6  7  8  9 10 11]
转换后数组的形状:
 [[0 1 2 3]
 [4 5 6 7]]
转换后数组的形状:
 [[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]


## 4. NumPy数组的矢量计算

### 4.1 数组的运算

In [143]:
# 相同形状的数组之间的运算
arr55 = np.arange(12).reshape(3,4)
arr56 = np.arange(12,24).reshape(3,4)
print('相同形状的数组之间的加法运算:\n',arr55+arr56)
print('相同形状的数组之间的减法运算:\n',arr55-arr56)
print('相同形状的数组之间的乘法运算:\n',arr55*arr56)
print('相同形状的数组之间的除法运算:\n',(arr55/arr56).round(2))
print('相同形状的数组之间的幂运算:\n',arr55**arr56.round(2))
print('相同形状的数组之间的取余运算:\n',arr55%arr56)
print('相同形状的数组之间的整除运算:\n',arr55//arr56)
print('数组arr55的平方根:\n',np.sqrt(arr55).round(2))
print('数组arr55的平方:\n',np.square(arr55))
print('数组arr55的相反数:\n',np.negative(arr55))
print('数组arr55的绝对值:\n',np.abs(arr55))
del arr55,arr56

相同形状的数组之间的加法运算:
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
相同形状的数组之间的减法运算:
 [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
相同形状的数组之间的乘法运算:
 [[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
相同形状的数组之间的除法运算:
 [[0.   0.08 0.14 0.2 ]
 [0.25 0.29 0.33 0.37]
 [0.4  0.43 0.45 0.48]]
相同形状的数组之间的幂运算:
 [[          0           1       16384    14348907]
 [          0 -1564725563  1159987200   442181591]
 [          0  1914644777 -1304428544  -122979837]]
相同形状的数组之间的取余运算:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
相同形状的数组之间的整除运算:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
数组arr55的平方根:
 [[0.   1.   1.41 1.73]
 [2.   2.24 2.45 2.65]
 [2.83 3.   3.16 3.32]]
数组arr55的平方:
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
数组arr55的相反数:
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
数组arr55的绝对值:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [147]:
# 不同形状的数组之间的运算（广播）
arr57 = np.arange(12).reshape(3,4)
arr58 = np.arange(1,5)
print('不同形状的数组之间的加法运算:\n',arr57+arr58)
print('不同形状的数组之间的减法运算:\n',arr57-arr58)
print('不同形状的数组之间的乘法运算:\n',arr57*arr58)
print('不同形状的数组之间的除法运算:\n',(arr57/arr58).round(2))
print('不同形状的数组之间的幂运算:\n',arr57**arr58.round(2))
print('不同形状的数组之间的取余运算:\n',arr57%arr58)
print('不同形状的数组之间的整除运算:\n',arr57//arr58)
print('数组arr57的平方根:\n',np.sqrt(arr57).round(2))
print('数组arr57的平方:\n',np.square(arr57))
print('数组arr57的相反数:\n',np.negative(arr57))
print('数组arr57的绝对值:\n',np.abs(arr57))
del arr57,arr58

不同形状的数组之间的加法运算:
 [[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]
不同形状的数组之间的减法运算:
 [[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]]
不同形状的数组之间的乘法运算:
 [[ 0  2  6 12]
 [ 4 10 18 28]
 [ 8 18 30 44]]
不同形状的数组之间的除法运算:
 [[0.   0.5  0.67 0.75]
 [4.   2.5  2.   1.75]
 [8.   4.5  3.33 2.75]]
不同形状的数组之间的幂运算:
 [[    0     1     8    81]
 [    4    25   216  2401]
 [    8    81  1000 14641]]
不同形状的数组之间的取余运算:
 [[0 1 2 3]
 [0 1 0 3]
 [0 1 1 3]]
不同形状的数组之间的整除运算:
 [[0 0 0 0]
 [4 2 2 1]
 [8 4 3 2]]
数组arr57的平方根:
 [[0.   1.   1.41 1.73]
 [2.   2.24 2.45 2.65]
 [2.83 3.   3.16 3.32]]
数组arr57的平方:
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
数组arr57的相反数:
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]]
数组arr57的绝对值:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 4.2 通用函数（ufunc）

In [154]:
# 通用函数（ufunc）
# 通用函数是一种对ndarray中的数据执行元素级运算的函数，可以将其看做简单函数（接受一个或多个标量值，并产生一个或多个标量值）的矢量化包装器
# 通用函数的主要目的是对ndarray中的数据执行快速的元素级运算，可以看做简单函数的矢量化包装器，接受一个或多个标量值，并产生一个或多个标量值
# 通用函数可以分为一元通用函数和二元通用函数
# 一元通用函数：abs、sqrt、square、exp、log、log10、log2、sign、ceil、floor、rint、modf、isnan、isfinite、isinf、cos、cosh、sin、sinh、tan、tanh、arccos、arccosh、arcsin、arcsinh、arctan、arctanh、logical_not
# 二元通用函数：add、subtract、multiply、divide、floor_divide、power、maximum、fmax、minimum、fmin、mod、copysign、greater、greater_equal、less、less_equal、equal、not_equal、logical_and、logical_or、logical_xor
# 通用函数的用法为np.通用函数名(数组名)
arr59 = np.arange(2,18).reshape(4,4)
print('数组arr59的平方根:\n',np.sqrt(arr59).round(2))
print('数组arr59的平方:\n',np.square(arr59))
print('数组arr59的相反数:\n',np.negative(arr59))
print('数组arr59的绝对值:\n',np.abs(arr59))
print('数组arr59的指数:\n',np.exp(arr59))
print('数组arr59的自然对数:\n',np.log(arr59))
print('数组arr59的以10为底的对数:\n',np.log10(arr59))
print('数组arr59的以2为底的对数:\n',np.log2(arr59))
print('数组arr59的符号:\n',np.sign(arr59))
print('数组arr59的上限:\n',np.ceil(arr59))
print('数组arr59的下限:\n',np.floor(arr59))
print('数组arr59的四舍五入:\n',np.rint(arr59))
print('数组arr59的小数部分和整数部分:\n',np.modf(arr59))
print('数组arr59的是否为非数值:\n',np.isnan(arr59))
print('数组arr59的是否为有限数值:\n',np.isfinite(arr59))
print('数组arr59的是否为无限数值:\n',np.isinf(arr59))
print('数组arr59的余弦值:\n',np.cos(arr59))
print('数组arr59的双曲余弦值:\n',np.cosh(arr59))
print('数组arr59的正弦值:\n',np.sin(arr59))
print('数组arr59的双曲正弦值:\n',np.sinh(arr59))
print('数组arr59的正切值:\n',np.tan(arr59))
print('数组arr59的双曲正切值:\n',np.tanh(arr59))
print('数组arr59的反双曲余弦值:\n',np.arccosh(arr59))
print('数组arr59的反双曲正弦值:\n',np.arcsinh(arr59))
print('数组arr59的反正切值:\n',np.arctan(arr59))
print('数组arr59的逻辑非:\n',np.logical_not(arr59))
print('数组arr59的加法:\n',np.add(arr59,arr59))
print('数组arr59的减法:\n',np.subtract(arr59,arr59))
print('数组arr59的数量积:\n',np.multiply(arr59,arr59))
print('数组arr59的矢量积:\n',np.dot(arr59,arr59))
print('数组arr59的除法:\n',np.divide(arr59,arr59))
print('数组arr59的幂运算:\n',np.power(arr59,arr59))
print('数组arr59的最大值:\n',np.maximum(arr59,arr59))
print('数组arr59的最小值:\n',np.minimum(arr59,arr59))
print('数组arr59的符号:\n',np.copysign(arr59,arr59))
print('数组arr59的大于运算:\n',np.greater(arr59,arr59))
print('数组arr59的大于等于运算:\n',np.greater_equal(arr59,arr59))
print('数组arr59的小于运算:\n',np.less(arr59,arr59))
print('数组arr59的小于等于运算:\n',np.less_equal(arr59,arr59))
print('数组arr59的等于运算:\n',np.equal(arr59,arr59))
print('数组arr59的不等于运算:\n',np.not_equal(arr59,arr59))
print('数组arr59的逻辑与运算:\n',np.logical_and(arr59,arr59))
print('数组arr59的逻辑或运算:\n',np.logical_or(arr59,arr59))
print('数组arr59的逻辑异或运算:\n',np.logical_xor(arr59,arr59))
del arr59

数组arr59的平方根:
 [[1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.  ]
 [3.16 3.32 3.46 3.61]
 [3.74 3.87 4.   4.12]]
数组arr59的平方:
 [[  4   9  16  25]
 [ 36  49  64  81]
 [100 121 144 169]
 [196 225 256 289]]
数组arr59的相反数:
 [[ -2  -3  -4  -5]
 [ -6  -7  -8  -9]
 [-10 -11 -12 -13]
 [-14 -15 -16 -17]]
数组arr59的绝对值:
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
数组arr59的指数:
 [[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]
 [2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05]
 [1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07]]
数组arr59的自然对数:
 [[0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665 2.56494936]
 [2.63905733 2.7080502  2.77258872 2.83321334]]
数组arr59的以10为底的对数:
 [[0.30103    0.47712125 0.60205999 0.69897   ]
 [0.77815125 0.84509804 0.90308999 0.95424251]
 [1.         1.04139269 1.07918125 1.11394335]
 [1.146

## 5. NumPy矩阵创建、计算及操作

NumPy矩阵  
NumPy矩阵是一个二维的、固定大小的数据结构，它包含在NumPy的子模块numpy.matlib中  
矩阵是一个二维的、固定大小的数据结构，它包含在NumPy的子模块numpy.matlib中  

### 5.1 矩阵的创建

In [2]:
# 矩阵的创建
## 使用字符串创建矩阵
# 使用字符串创建矩阵的格式为np.mat(字符串)
# 使用字符串创建矩阵时，字符串中的每个元素之间用空格隔开，每行元素之间用分号隔开
# 使用字符串创建矩阵时，字符串中的每个元素必须是数值型，否则会报错
np.mat('1 2 3;4 5 6;7 8 9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
## 使用嵌套列表创建矩阵
# 使用嵌套列表创建矩阵的格式为np.mat(嵌套列表)
# 使用嵌套列表创建矩阵时，嵌套列表中的每个元素之间用逗号隔开，每行元素之间用分号隔开
# 使用嵌套列表创建矩阵时，嵌套列表中的每个元素可以是数值型，也可以是字符串型
np.mat([[1,2,3],[4,5,6],[7,8,9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
## 使用数组创建矩阵
# 使用数组创建矩阵的格式为np.mat(数组)
# 使用数组创建矩阵时，数组中的每个元素之间用逗号隔开，每行元素之间用分号隔开
# 使用数组创建矩阵时，数组中的每个元素可以是数值型，也可以是字符串型
np.mat(np.arange(1,10).reshape(3,3))

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
## 使用matrix函数创建矩阵
# 使用matrix函数创建矩阵的格式为np.matrix(数组)
# 使用matrix函数创建矩阵时，数组中的每个元素之间用逗号隔开，每行元素之间用分号隔开
# 使用matrix函数创建矩阵时，数组中的每个元素可以是数值型，也可以是字符串型
np.matrix(np.arange(1,10).reshape(3,3))

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
## 使用bmat函数创建矩阵
# 使用bmat函数创建矩阵的格式为np.bmat(嵌套列表)
# 使用bmat函数创建矩阵时，嵌套列表中的每个元素之间用逗号隔开，每行元素之间用分号隔开
# 使用bmat函数创建矩阵时，嵌套列表中的每个元素可以是数值型，也可以是字符串型
mat1 = np.matrix(np.arange(1,10).reshape(3,3))
mat2 = np.matrix(np.arange(1,10).reshape(3,3))
np.bmat([mat1,mat2])
del mat1,mat2

### 5.2 矩阵的计算及操作

In [38]:
# 矩阵的属性
## 矩阵的维度
# 矩阵的维度可以通过矩阵的shape属性获得
# 矩阵的维度是一个元组，元组中的第一个元素表示矩阵的行数，第二个元素表示矩阵的列数
mat = np.mat('1 2 3;4 5 6;7 8 9')
print(mat.shape,'\n',mat)
del mat

(3, 3) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
# 矩阵的计算
mat1 = np.mat('1 2 3;4 5 6;7 8 9')
mat2 = np.mat('1 2 3;4 5 6;7 8 9')
print('矩阵相加\n',mat1+mat2)
print('矩阵数量积\n',mat1*mat2)
print('矩阵向量积\n',np.dot(mat1,mat2))
del mat1,mat2

矩阵相加
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
矩阵数量积
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
矩阵向量积
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [47]:
# 矩阵的操作
## 矩阵的转置
# 矩阵的转置可以通过矩阵的T属性获得
# 矩阵的转置是将矩阵的行和列互换
mat = np.mat('1 2 3;4 5 6;7 8 9')
print('矩阵\n',mat)
print('矩阵的转置\n',mat.T)
# 取矩阵第一行的值
print('矩阵第一行的值\n',mat[0])
# 取矩阵第一列的值
print('矩阵第一列的值\n',mat[:,0])
del mat

矩阵
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
矩阵的转置
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
矩阵第一行的值
 [[1 2 3]]
矩阵第一列的值
 [[1]
 [4]
 [7]]


## 6. 随机数生成

In [60]:
# rand函数生成随机数
# rand函数可以生成一个0到1之间的随机数
# rand函数的格式为np.random.rand(维度)
# rand函数的参数维度可以是一个整数，也可以是一个元组
# rand函数生成的随机数是均匀分布的
# rand函数生成的随机数是浮点型的
# rand函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)# 设置随机数种子
np.random.rand(3,3)

array([[0.02672935, 0.79279632, 0.25236475],
       [0.79726584, 0.30721521, 0.56233201],
       [0.64530382, 0.50804097, 0.3991289 ]])

In [68]:
# randn函数生成随机数
# randn函数可以生成一个服从标准正态分布的随机数
# randn函数的格式为np.random.randn(维度)
# randn函数的参数维度可以是一个整数，也可以是一个元组
# randn函数生成的随机数是服从标准正态分布的
# randn函数生成的随机数是浮点型的
# randn函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.randn(3,3)

array([[ 0.77817408, -0.64825252,  0.58478833],
       [-1.80867401,  0.12277205,  2.21854379],
       [-1.4889872 , -0.62538366, -2.25033158]])

In [71]:
# randint函数生成随机数
# randint函数可以生成一个指定范围内的随机整数
# randint函数的格式为np.random.randint(最小值,最大值,维度)
# randint函数的参数维度可以是一个整数，也可以是一个元组
# randint函数生成的随机数是均匀分布的
# randint函数生成的随机数是整数型的
# randint函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.randint(1,10,(3,3))

array([[2, 4, 4],
       [3, 6, 7],
       [7, 3, 6]])

In [72]:
# random函数生成随机数
# random函数可以生成一个0到1之间的随机数
# random函数的格式为np.random.random(维度)
# random函数的参数维度可以是一个整数，也可以是一个元组
# random函数生成的随机数是均匀分布的
# random函数生成的随机数是浮点型的
# random函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.random((3,3))

array([[0.02672935, 0.79279632, 0.25236475],
       [0.79726584, 0.30721521, 0.56233201],
       [0.64530382, 0.50804097, 0.3991289 ]])

In [73]:
# choice函数生成随机数
# choice函数可以从指定的一维数组中生成随机数
# choice函数的格式为np.random.choice(一维数组,维度)
# choice函数的参数维度可以是一个整数，也可以是一个元组
# choice函数生成的随机数是均匀分布的
# choice函数生成的随机数是浮点型的
# choice函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.choice(np.arange(1,10),3)

array([2, 4, 4])

In [74]:
# shuffle函数生成随机数
# shuffle函数可以对指定的一维数组进行随机排序
# shuffle函数的格式为np.random.shuffle(一维数组)
# shuffle函数生成的随机数是均匀分布的
# shuffle函数生成的随机数是浮点型的
# shuffle函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
arr = np.arange(1,10)
np.random.shuffle(arr)
print(arr)
del arr

[1 9 7 6 5 3 8 4 2]


In [75]:
# normal函数生成随机数
# normal函数可以生成一个服从正态分布的随机数
# normal函数的格式为np.random.normal(均值,标准差,维度)
# normal函数的参数维度可以是一个整数，也可以是一个元组
# normal函数生成的随机数是服从正态分布的
# normal函数生成的随机数是浮点型的
# normal函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.normal(0,1,(3,3))

array([[ 0.77817408, -0.64825252,  0.58478833],
       [-1.80867401,  0.12277205,  2.21854379],
       [-1.4889872 , -0.62538366, -2.25033158]])

In [76]:
# uniform函数生成随机数
# uniform函数可以生成一个指定范围内的随机数
# uniform函数的格式为np.random.uniform(最小值,最大值,维度)
# uniform函数的参数维度可以是一个整数，也可以是一个元组
# uniform函数生成的随机数是均匀分布的
# uniform函数生成的随机数是浮点型的
# uniform函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.uniform(1,10,(3,3))

array([[1.24056418, 8.1351669 , 3.27128278],
       [8.17539258, 3.76493691, 6.06098812],
       [6.80773437, 5.57236875, 4.59216011]])

In [78]:
# binomial函数生成随机数
# binomial函数可以生成一个服从二项分布的随机数
# binomial函数的格式为np.random.binomial(试验次数,事件发生概率,维度)
# binomial函数的参数维度可以是一个整数，也可以是一个元组
# binomial函数生成的随机数是服从二项分布的
# binomial函数生成的随机数是整数型的
# binomial函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.binomial(10,0.5,(3,3))

array([[2, 6, 4],
       [6, 4, 5],
       [6, 5, 5]])

In [79]:
# beta函数生成随机数
# beta函数可以生成一个服从beta分布的随机数
# beta函数的格式为np.random.beta(α,β,维度)
# beta函数的参数维度可以是一个整数，也可以是一个元组
# beta函数生成的随机数是服从beta分布的
# beta函数生成的随机数是浮点型的
# beta函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.beta(1,1,(3,3))

array([[0.03261564, 0.3533048 , 0.60569235],
       [0.57877393, 0.74355064, 0.73998427],
       [0.90775507, 0.22959591, 0.21336338]])

In [80]:
# gamma函数生成随机数
# gamma函数可以生成一个服从gamma分布的随机数
# gamma函数的格式为np.random.gamma(α,β,维度)
# gamma函数的参数维度可以是一个整数，也可以是一个元组
# gamma函数生成的随机数是服从gamma分布的
# gamma函数生成的随机数是浮点型的
# gamma函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.gamma(1,1,(3,3))

array([[0.02709308, 1.57405302, 0.29084006],
       [1.59585973, 0.36703588, 0.82629468],
       [1.03649368, 0.70935984, 0.50937485]])

In [81]:
# poisson函数生成随机数
# poisson函数可以生成一个服从泊松分布的随机数
# poisson函数的格式为np.random.poisson(λ,维度)
# poisson函数的参数维度可以是一个整数，也可以是一个元组
# poisson函数生成的随机数是服从泊松分布的
# poisson函数生成的随机数是整数型的
# poisson函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.poisson(1,(3,3))

array([[0, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [82]:
# chisquare函数生成随机数
# chisquare函数可以生成一个服从卡方分布的随机数
# chisquare函数的格式为np.random.chisquare(自由度,维度)
# chisquare函数的参数维度可以是一个整数，也可以是一个元组
# chisquare函数生成的随机数是服从卡方分布的
# chisquare函数生成的随机数是浮点型的
# chisquare函数生成的随机数是伪随机数，每次生成的随机数都是固定的
np.random.seed(1012)
np.random.chisquare(1,(3,3))

array([[1.42891665e-03, 1.27375938e-01, 1.88762374e-01],
       [9.02289913e-01, 3.18607760e-01, 5.95243681e-01],
       [1.81308214e+00, 9.24319131e-01, 3.25810225e-01]])